
services:
  # MySQL Database Service
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: crud_app
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crud-network

  # Backend Service
  backend:
    build: ./backend
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=crud_app
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    networks:
      - crud-network

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - crud-network
    depends_on:
      - backend

# Named volume to persist MySQL data
volumes:
  mysql-data:

networks:
  crud-network:
